spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keep-db
    username: admin
    password: admin
  liquibase:
    change-log: classpath:liquibase/master.xml
  #    drop-first: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

application:
  module:
    documento: localhost:8081/api/documento
  elasticsearch:
    url: localhost:9200
