services:
  elasticsearch:
    image: elasticsearch:7.13.2
    container_name: keep-elasticsearch
    ports:
      - 9200:9200
    mem_limit: 1024M
    environment:
      - "discovery.type=single-node"
