services:
  minio:
    image: minio/minio
    container_name: keep-minio
    ports:
      - 9000:9000
    mem_limit: 1024M
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data